spring.application.name=event-management-api

# PostgreSQL Connection Settings
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=logs/event-api.log
logging.level.root=INFO
logging.level.org.example.eventmanagementapi=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.security.jwt.refresh-token.expiration=${REFRESH_TOKEN_EXPIRATION}
application.security.jwt.issuer=${JWT_ISSUER}
application.security.jwt.audience=${JWT_AUDIENCE}

# Redis Config
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.refresh-token.prefix=${REDIS_REFRESH_TOKEN_PREFIX}
spring.data.redis.refresh-token.version-prefix=${REDIS_REFRESH_TOKEN_VERSION_PREFIX}